"""Add artist column to versions table

Revision ID: 9d76c798b32f
Revises: 6e69d94d8db6
Create Date: 2023-11-16 14:16:33.330066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d76c798b32f'
down_revision: Union[str, None] = '6e69d94d8db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'BPM')
    op.drop_column('versions', 'original_artist')
    op.drop_column('versions', 'path_to_file')
    op.add_column('versions', sa.Column('bpm', sa.Float(), nullable=True))
    op.add_column('tracks', sa.Column('bpm', sa.Float(), nullable=True))
    op.add_column('versions', sa.Column('artist', sa.String(), nullable=True))
    op.add_column('versions', sa.Column('file_path', sa.String(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versions', sa.Column('path_to_file', sa.VARCHAR(), nullable=True))
    op.add_column('versions', sa.Column('original_artist', sa.VARCHAR(), nullable=True))
    op.drop_column('versions', 'bpm')
    op.drop_column('versions', 'file_path')
    op.drop_column('versions', 'artist')
    op.add_column('tracks', sa.Column('BPM', sa.FLOAT(), nullable=True))
    op.drop_column('tracks', 'bpm')
    # ### end Alembic commands ###
