"""Update cascade rules

Revision ID: beb069fcbd63
Revises: 9d76c798b32f
Create Date: 2023-11-20 14:52:06.432156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb069fcbd63'
down_revision: Union[str, None] = '9d76c798b32f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tracks_current_version_id_versions', 'tracks', type_='foreignkey')
    op.create_foreign_key('fk_tracks_current_version_id_versions', 'tracks', 'versions', ['current_version_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('length', sa.VARCHAR(), nullable=True),
    sa.Column('key', sa.VARCHAR(), nullable=True),
    sa.Column('date_created', sa.DATE(), nullable=True),
    sa.Column('date_added', sa.DATE(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=True),
    sa.Column('path_to_ableton_project', sa.VARCHAR(), nullable=True),
    sa.Column('artist', sa.VARCHAR(), nullable=True),
    sa.Column('current_version_id', sa.INTEGER(), nullable=True),
    sa.Column('bpm', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['current_version_id'], ['versions.id'], name='fk_tracks_current_version_id_versions'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('track_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('length', sa.VARCHAR(), nullable=True),
    sa.Column('key', sa.VARCHAR(), nullable=True),
    sa.Column('date_created', sa.DATE(), nullable=True),
    sa.Column('date_added', sa.DATE(), nullable=True),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('path_to_ableton_project', sa.VARCHAR(), nullable=True),
    sa.Column('bpm', sa.FLOAT(), nullable=True),
    sa.Column('artist', sa.VARCHAR(), nullable=True),
    sa.Column('file_path', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('developer_mode', sa.BOOLEAN(), nullable=True),
    sa.Column('dark_mode', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('developer_mode', sa.BOOLEAN(), nullable=True),
    sa.Column('dark_mode', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
